baseurl = "/"
languageCode = "en-US"
title = "Jeremy Meiss"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
#  post = "/:year/:month/:day/:slug"
  post = "/:slug"

[params]
  avatar = "profile.jpg"
  author = "Jeremy Meiss"
  description = "DevRel Professional, Community Fiend, Herder of Cats"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jerdog"
#  Email         = "email@example.com"
  Twitter       = "IAmJerdog"
  LinkedIn      = "jeremymeiss"
#  Stackoverflow = "username"
  Medium        = "jeremymeiss"
  Telegram      = "IAmJerdog"
  Gitlab        = "jerdog"
  DevTo         = "jerdog"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "events"
  identifier = "events"
  weight = 200
  url = "events"
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
